package com.ubosque.grupo4N.modelo;
// Generated 24/05/2017 11:53:12 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Autorizacion generated by hbm2java
 */
@Entity
@Table(name = "autorizacion", catalog = "heartscits")
public class Autorizacion implements java.io.Serializable {

	private Integer idAutorizacion;
	private Paciente paciente;
	private String nitAutorizacion;
	private Date fechaExpedicionAutorizacion;
	private String descripcionAutorizacion;
	private String estado;
	private Set<Cita> citas = new HashSet<Cita>(0);

	public Autorizacion() {
	}

	public Autorizacion(Paciente paciente, String nitAutorizacion, Date fechaExpedicionAutorizacion,
			String descripcionAutorizacion, String estado) {
		this.paciente = paciente;
		this.nitAutorizacion = nitAutorizacion;
		this.fechaExpedicionAutorizacion = fechaExpedicionAutorizacion;
		this.descripcionAutorizacion = descripcionAutorizacion;
		this.estado = estado;
	}

	public Autorizacion(Paciente paciente, String nitAutorizacion, Date fechaExpedicionAutorizacion,
			String descripcionAutorizacion, String estado, Set<Cita> citas) {
		this.paciente = paciente;
		this.nitAutorizacion = nitAutorizacion;
		this.fechaExpedicionAutorizacion = fechaExpedicionAutorizacion;
		this.descripcionAutorizacion = descripcionAutorizacion;
		this.estado = estado;
		this.citas = citas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idAutorizacion", unique = true, nullable = false)
	public Integer getIdAutorizacion() {
		return this.idAutorizacion;
	}

	public void setIdAutorizacion(Integer idAutorizacion) {
		this.idAutorizacion = idAutorizacion;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "fkAutorizacionPaciente", nullable = false)
	public Paciente getPaciente() {
		return this.paciente;
	}

	public void setPaciente(Paciente paciente) {
		this.paciente = paciente;
	}

	@Column(name = "nitAutorizacion", nullable = false, length = 50)
	public String getNitAutorizacion() {
		return this.nitAutorizacion;
	}

	public void setNitAutorizacion(String nitAutorizacion) {
		this.nitAutorizacion = nitAutorizacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaExpedicionAutorizacion", nullable = false, length = 10)
	public Date getFechaExpedicionAutorizacion() {
		return this.fechaExpedicionAutorizacion;
	}

	public void setFechaExpedicionAutorizacion(Date fechaExpedicionAutorizacion) {
		this.fechaExpedicionAutorizacion = fechaExpedicionAutorizacion;
	}

	@Column(name = "DescripcionAutorizacion", nullable = false, length = 100)
	public String getDescripcionAutorizacion() {
		return this.descripcionAutorizacion;
	}

	public void setDescripcionAutorizacion(String descripcionAutorizacion) {
		this.descripcionAutorizacion = descripcionAutorizacion;
	}

	@Column(name = "estado", nullable = true, length = 100)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "autorizacion")
	public Set<Cita> getCitas() {
		return this.citas;
	}

	public void setCitas(Set<Cita> citas) {
		this.citas = citas;
	}

}
