package com.ubosque.grupo4N.modelo;
// Generated 12/05/2017 11:19:54 AM by Hibernate Tools 5.2.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cita generated by hbm2java
 */
@Entity
@Table(name = "cita", catalog = "heartscits")
public class Cita implements java.io.Serializable {

	private Integer idCita;
	private Autorizacion autorizacion;
	private Empleado empleado;
	private Tiposervicio tiposervicio;
	private Date fechaCita;
	private String estadoCita;

	public Cita() {
	}

	public Cita(Empleado empleado, Date fechaCita, String estadoCita) {
		this.empleado = empleado;
		this.fechaCita = fechaCita;
		this.estadoCita = estadoCita;
	}

	public Cita(Autorizacion autorizacion, Empleado empleado, Tiposervicio tiposervicio, Date fechaCita,
			String estadoCita) {
		this.autorizacion = autorizacion;
		this.empleado = empleado;
		this.tiposervicio = tiposervicio;
		this.fechaCita = fechaCita;
		this.estadoCita = estadoCita;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idCita", unique = true, nullable = false)
	public Integer getIdCita() {
		return this.idCita;
	}

	public void setIdCita(Integer idCita) {
		this.idCita = idCita;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "fkCitaAutorizacion")
	public Autorizacion getAutorizacion() {
		return this.autorizacion;
	}

	public void setAutorizacion(Autorizacion autorizacion) {
		this.autorizacion = autorizacion;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "fkCitaEmpleado", nullable = false)
	public Empleado getEmpleado() {
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "fkCitaTipoServicio")
	public Tiposervicio getTiposervicio() {
		return this.tiposervicio;
	}

	public void setTiposervicio(Tiposervicio tiposervicio) {
		this.tiposervicio = tiposervicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaCita", nullable = false, length = 10)
	public Date getFechaCita() {
		return this.fechaCita;
	}

	public void setFechaCita(Date fechaCita) {
		this.fechaCita = fechaCita;
	}

	@Column(name = "estadoCita", nullable = false, length = 10)
	public String getEstadoCita() {
		return this.estadoCita;
	}

	public void setEstadoCita(String estadoCita) {
		this.estadoCita = estadoCita;
	}

}
