package com.ubosque.grupo4N.modelo;
// Generated 12/05/2017 11:19:54 AM by Hibernate Tools 5.2.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Duracion generated by hbm2java
 */
@Entity
@Table(name = "duracion", catalog = "heartscits", uniqueConstraints = @UniqueConstraint(columnNames = "tiempo"))
public class Duracion implements java.io.Serializable {

	private Integer idDuracion;
	private Date tiempo;
	private Set<Tiposervicio> tiposervicios = new HashSet<Tiposervicio>(0);

	public Duracion() {
	}

	public Duracion(Date tiempo) {
		this.tiempo = tiempo;
	}

	public Duracion(Date tiempo, Set<Tiposervicio> tiposervicios) {
		this.tiempo = tiempo;
		this.tiposervicios = tiposervicios;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idDuracion", unique = true, nullable = false)
	public Integer getIdDuracion() {
		return this.idDuracion;
	}

	public void setIdDuracion(Integer idDuracion) {
		this.idDuracion = idDuracion;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "tiempo", unique = true, nullable = false, length = 8)
	public Date getTiempo() {
		return this.tiempo;
	}

	public void setTiempo(Date tiempo) {
		this.tiempo = tiempo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "duracion")
	public Set<Tiposervicio> getTiposervicios() {
		return this.tiposervicios;
	}

	public void setTiposervicios(Set<Tiposervicio> tiposervicios) {
		this.tiposervicios = tiposervicios;
	}

}
