package com.ubosque.grupo4N.modelo;
// Generated 12/05/2017 11:19:54 AM by Hibernate Tools 5.2.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Paciente generated by hbm2java
 */
@Entity
@Table(name = "paciente", catalog = "heartscits", uniqueConstraints = @UniqueConstraint(columnNames = "documentoPaciente"))
public class Paciente implements java.io.Serializable {

	private Integer idPaciente;
	private String nombresPaciente;
	private String apellidosPaciente;
	private String tipoDocumentoPaciente;
	private int documentoPaciente;
	private String direccionPaciente;
	private Integer telefonoPaciente;
	private String ipsEps;
	private Date fechaNacimientoPaciente;
	private String correoPaciente;
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);
	private Set<Autorizacion> autorizacions = new HashSet<Autorizacion>(0);

	public Paciente() {
	}

	public Paciente(String nombresPaciente, String apellidosPaciente, String tipoDocumentoPaciente,
			int documentoPaciente, Date fechaNacimientoPaciente, String correoPaciente) {
		this.nombresPaciente = nombresPaciente;
		this.apellidosPaciente = apellidosPaciente;
		this.tipoDocumentoPaciente = tipoDocumentoPaciente;
		this.documentoPaciente = documentoPaciente;
		this.fechaNacimientoPaciente = fechaNacimientoPaciente;
		this.correoPaciente = correoPaciente;
	}

	public Paciente(String nombresPaciente, String apellidosPaciente, String tipoDocumentoPaciente,
			int documentoPaciente, String direccionPaciente, Integer telefonoPaciente, String ipsEps,
			Date fechaNacimientoPaciente, String correoPaciente, Set<Usuario> usuarios,
			Set<Autorizacion> autorizacions) {
		this.nombresPaciente = nombresPaciente;
		this.apellidosPaciente = apellidosPaciente;
		this.tipoDocumentoPaciente = tipoDocumentoPaciente;
		this.documentoPaciente = documentoPaciente;
		this.direccionPaciente = direccionPaciente;
		this.telefonoPaciente = telefonoPaciente;
		this.ipsEps = ipsEps;
		this.fechaNacimientoPaciente = fechaNacimientoPaciente;
		this.correoPaciente = correoPaciente;
		this.usuarios = usuarios;
		this.autorizacions = autorizacions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idPaciente", unique = true, nullable = false)
	public Integer getIdPaciente() {
		return this.idPaciente;
	}

	public void setIdPaciente(Integer idPaciente) {
		this.idPaciente = idPaciente;
	}

	@Column(name = "nombresPaciente", nullable = false, length = 50)
	public String getNombresPaciente() {
		return this.nombresPaciente;
	}

	public void setNombresPaciente(String nombresPaciente) {
		this.nombresPaciente = nombresPaciente;
	}

	@Column(name = "apellidosPaciente", nullable = false, length = 50)
	public String getApellidosPaciente() {
		return this.apellidosPaciente;
	}

	public void setApellidosPaciente(String apellidosPaciente) {
		this.apellidosPaciente = apellidosPaciente;
	}

	@Column(name = "tipoDocumentoPaciente", nullable = false, length = 25)
	public String getTipoDocumentoPaciente() {
		return this.tipoDocumentoPaciente;
	}

	public void setTipoDocumentoPaciente(String tipoDocumentoPaciente) {
		this.tipoDocumentoPaciente = tipoDocumentoPaciente;
	}

	@Column(name = "documentoPaciente", unique = true, nullable = false)
	public int getDocumentoPaciente() {
		return this.documentoPaciente;
	}

	public void setDocumentoPaciente(int documentoPaciente) {
		this.documentoPaciente = documentoPaciente;
	}

	@Column(name = "direccionPaciente", length = 50)
	public String getDireccionPaciente() {
		return this.direccionPaciente;
	}

	public void setDireccionPaciente(String direccionPaciente) {
		this.direccionPaciente = direccionPaciente;
	}

	@Column(name = "telefonoPaciente")
	public Integer getTelefonoPaciente() {
		return this.telefonoPaciente;
	}

	public void setTelefonoPaciente(Integer telefonoPaciente) {
		this.telefonoPaciente = telefonoPaciente;
	}

	@Column(name = "IPS_EPS", length = 50)
	public String getIpsEps() {
		return this.ipsEps;
	}

	public void setIpsEps(String ipsEps) {
		this.ipsEps = ipsEps;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FechaNacimientoPaciente", nullable = false, length = 10)
	public Date getFechaNacimientoPaciente() {
		return this.fechaNacimientoPaciente;
	}

	public void setFechaNacimientoPaciente(Date fechaNacimientoPaciente) {
		this.fechaNacimientoPaciente = fechaNacimientoPaciente;
	}

	@Column(name = "correoPaciente", nullable = false, length = 100)
	public String getCorreoPaciente() {
		return this.correoPaciente;
	}

	public void setCorreoPaciente(String correoPaciente) {
		this.correoPaciente = correoPaciente;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "paciente")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "paciente")
	public Set<Autorizacion> getAutorizacions() {
		return this.autorizacions;
	}

	public void setAutorizacions(Set<Autorizacion> autorizacions) {
		this.autorizacions = autorizacions;
	}

}
