package com.ubosque.grupo4N.modelo;
// Generated 12/05/2017 02:06:01 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.ubosque.grupo4N.mb.Herramientas;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", catalog = "heartscits", uniqueConstraints = @UniqueConstraint(columnNames = "usuario"))
public class Usuario implements java.io.Serializable {

	private Integer idUsuario;
	private Empleado empleado;
	private Paciente paciente;
	private Rol rol;
	private String usuario;
	private String contrasena;

	public Usuario() {
	}

	public Usuario(Rol rol, String usuario, String contrasena) {
		this.rol = rol;
		this.usuario = usuario;
		this.contrasena = contrasena;
	}

	public Usuario(Empleado empleado, Paciente paciente, Rol rol, String usuario, String contrasena) {
		this.empleado = empleado;
		this.paciente = paciente;
		this.rol = rol;
		this.usuario = usuario;
		this.contrasena = contrasena;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idUsuario", unique = true, nullable = false)
	public Integer getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "fkUsuarioEmpleado")
	public Empleado getEmpleado() {
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "fkUsuarioPaciente")
	public Paciente getPaciente() {
		return this.paciente;
	}

	public void setPaciente(Paciente paciente) {
		this.paciente = paciente;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "fkUsuarioRol", nullable = false)
	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

	@Column(name = "usuario", unique = true, nullable = false, length = 25)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Column(name = "contrasena", nullable = false, length = 500)
	public String getContrasena() throws Exception {
		return this.contrasena;
	}

	public void setContrasena(String contrasena) {
		this.contrasena = contrasena;
	}

}
